version: "3"

services:
  client:
    container_name: social-client-dev
    image: social-client-dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    command: yarn start
