version: "3"

services:
  client:
    container_name: social-client-dev
    image: social-client-dev
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/user/src/client
    command: yarn start
