version: "3"

services:
  client:
    container_name: social-client-dev
    image: social-client-dev
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/user/src/client
    depends_on:
      - server
  server:
    container_name: social-server-dev
    image: social-server-dev
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/user/src/server
    environment:
      PORT: 8080
      API_BASE_URL: http://localhost:8080
      CLIENT_BASE_URL: http://localhost:3000
      USERDATABASE: mongodb://mongo:27017/Social
      SECRET_KEY: SECxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxSEC
      GOOGLE_CLIENT_ID: googleclientid
      GOOGLE_CLIENT_SECRET: googleclientsecret
      FIREBASE_STORAGEBUCKET: firebasestoragebucket
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    volumes:
      - mongo:/data/db
    ports:
      - "2717:27017"
volumes:
  mongo: {}
